### PR TITLE
Modified common.shader including missing essential shaders and new shader images.

### PR DESCRIPTION
**Pull request by NeonKnightOA**
From now on, I'll be introducing changes through pull-requests instead of directly.

Here's the first one.

### CODE REVIEW

**Comment by illwieckz** [comment]
It would be better to ship those `common` textures as a `pk3` file with the game or as an extra file to download to avoid to bloat the gamepack if possible, to not uselessly weightens the radiant distribution.

See how Unvanquished does with the `tex-common_2.1.dpk` file as an example ([here is the repository](http://github.com/UnvanquishedAssets/tex-common_src.dpkdir)).

**Comment by NeonKnightOA** [comment]
While I agree, the problem is that OA won't see a new version in quite a long time, as it's currently undergoing a content reboot (years of uncontrolled "throw everything you can find as long as it's FOSS" left a big mess we're trying to sanitize). That's why I've added the editor-only shaders to this gamepack.

**Comment by illwieckz** [comment]
I understand. Have you seen #3? :-)

**Comment by illwieckz** [comment]
I just thought about one thing. Even if you ship those files with gamepack, the `q3map2` map compiler will not find them, because the map compiler does not look at gamepack. While being annoying, a separate pk3 the user put himself in its `baseoa` directory would work.

**Comment by NeonKnightOA** [comment]
Checked, but can't take care of it ATM.

As for the pk3, yeah, it should work, I guess.

**Pull request closed without merging**
